# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: fae31a0
_src_path: .
author_email: you@example.com
author_name: Your Name
project_description: A TypeScript project
project_name: typescript-template
typescript_strict: true
use_devcontainer: true
use_github_actions: true
use_vscode: true
