services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace

    volumes:
      - ..:/workspace
      - math_king_of_the_hill_extensions:/home/vscode/.vscode-server/extensions
      - math_king_of_the_hill_commandhistory:/home/vscode/commandhistory
      - math_king_of_the_hill_cache:/home/vscode/.cache
      - math_king_of_the_hill_bun:/home/vscode/.bun
      - /workspace/node_modules

    # Keep container running
    command: sleep infinity

volumes:
  math_king_of_the_hill_extensions:
  math_king_of_the_hill_commandhistory:
  math_king_of_the_hill_cache:
  math_king_of_the_hill_bun:
